export type {
  BleConnectionAdapter,
  BleConnectionOptions,
  BleConnectionState,
  BleGattCharacteristicAddress,
  BleGattService,
  BleScanAdapterState,
  BleDedupeMode,
  BleDistanceModel,
  BleRetryPolicy,
  BleScanError,
  BleScanEvent,
  BleScanFilter,
  BleScanManager,
  BleParsedManufacturerData,
  BleRankingWeights,
  BleScanSnapshot,
  BleScanConfig,
  BleScanResult,
  ManufacturerParser,
} from './types'
export {
  bleScanManager,
  connectBleDevice,
  disconnectBleDevice,
  discoverBleServices,
  estimateDistance,
  ensureBleScanPermissions,
  getBleAdapterState,
  getBleScanSnapshot,
  readBleCharacteristic,
  rankDevices,
  registerManufacturerParser,
  setBleCharacteristicNotification,
  startBleScan,
  stopBleScan,
  subscribeBleScan,
  unregisterManufacturerParser,
  writeBleCharacteristic,
} from './runtime'
export {
  createConnectionStateGuard,
  createDiscoveryCache,
  createNotificationManager,
  discoverServicesWithCache,
  readWithRetry,
  safeConnect,
  safeDisconnect,
  withRetry,
  withTimeout,
  writeWithRetry,
} from './connectionUtils'
